-- unrealUI :: core/auradata.lua
--
-- Base durations for named auras, and the adjustments that make a handful of
-- them depend on the player rather than on the spell alone. This file is data
-- plus one lookup; the tracking that turns a duration into a running timer
-- lives in modules/auras.lua.
--
-- ---------------------------------------------------------------------------
-- Why a table exists at all
-- ---------------------------------------------------------------------------
--
-- knowledge.json / auras.no_native_debuff_expiry_time (SUPPORTED,
-- BEHAVIOR_VERIFIED, RUNTIME_MEASURED): a target aura's remaining time cannot
-- be read from this client. UnitDebuff returns (texture, count, debuffType)
-- and nothing more, and GameTooltip:SetUnitDebuff produces exactly two lines --
-- the name and a static description -- with no timer anywhere in it, measured
-- against a live warlock Immolate. The client's only remaining-time API,
-- GetPlayerBuffTimeLeft, is indexed by GetPlayerBuff and covers the player's
-- own auras only; there is no target equivalent.
--
-- That record's own solution text says a target timer "would require
-- reproducing pfUI's whole duration-table + combat-log-timestamp
-- reconstruction ... which is out of scope unless explicitly requested". It
-- was explicitly requested, so this is that reconstruction -- kept to the
-- smallest shape that answers it.
--
-- The durations come from UnrealPfUI's libs/libdebuff.lua duration table
-- (env/locales_enUS.lua, DBC-extracted), which is WORKING_SOURCE evidence per
-- .claude/rules/unreal-pfui.md: a working implementation on this same client,
-- not runtime verification. Only the data is taken. pfUI's library framework,
-- its combat-log parsers, its pending-spell machinery and its cast hooks are
-- not reproduced -- modules/auras.lua stamps an aura when it first observes it,
-- which needs none of them.
--
-- ---------------------------------------------------------------------------
-- What this means for accuracy
-- ---------------------------------------------------------------------------
--
--   * A duration here is the spell's full duration at max rank. Rank is not
--     recoverable for another unit's aura, and pfUI's own display path passes
--     rank as nil for the same reason (libdebuff:UnitDebuff, "no backport"),
--     so a low-rank aura reads long.
--   * The table is debuff-weighted because that is what pfUI's extractor
--     produced. Many buffs are absent; an aura with no entry here simply gets
--     no timer and no wipe, which is the honest result rather than a guess.
--   * Nothing here is verified against this server's own spell data. If
--     Emberveil retuned a duration, this table is wrong for that spell and the
--     timer restarts when the aura outlives it -- see RestampExpired in
--     modules/auras.lua.
--
-- ---------------------------------------------------------------------------
-- Local budget
-- ---------------------------------------------------------------------------
--
-- rules/unreal-ui.md caps a file's main chunk at 200 top-level locals and a
-- file that overruns it fails to load in silence. The 900-plus entries below
-- are one table on one local, which is the table form that rule prescribes.

local U = UnrealUI

-- Seconds, keyed by the aura name the tooltip scanner reads off line 1.
local DURATION = {
  ["AE Charm"] = 300,
  ["Abomination Spit"] = 10,
  ["Acid Slime"] = 30,
  ["Acid Spit"] = 30,
  ["Acid Splash"] = 30,
  ["Acid Spray"] = 10,
  ["Acid Volley"] = 25,
  ["Acid of Hakkar"] = 60,
  ["Advanced Target Dummy Spawn Effect"] = 10,
  ["Aftermath"] = 5,
  ["Agility VIII"] = 3600,
  ["Agonizing Pain"] = 15,
  ["Air Bubbles"] = 10,
  ["Amplify Damage"] = 10,
  ["Amplify Flames"] = 30,
  ["Ancient Despair"] = 5,
  ["Ancient Dread"] = 900,
  ["Ancient Hysteria"] = 900,
  ["Anub'Rekhan's Aura"] = 5,
  ["Aquatic Miasma"] = 3600,
  ["Arantir's Rage"] = 6,
  ["Arcane Burst"] = 8,
  ["Arcane Intellect"] = 1800,
  ["Arcane Missiles"] = 5,
  ["Arcane Weakness"] = 45,
  ["Armor IV"] = 3600,
  ["Armor Shatter"] = 45,
  ["Arugal's Curse"] = 10,
  ["Arugal's Gift"] = 300,
  ["Aspect of Arlokk"] = 2,
  ["Aspect of Jeklik"] = 5,
  ["Aspect of Mar'li"] = 6,
  ["Aspect of Venoxis"] = 10,
  ["Atal'ai Poison"] = 30,
  ["Attack Order"] = 10,
  ["Attract Rager"] = 2,
  ["Aura Leech (PT)"] = 15,
  ["Aura of Agony"] = 8,
  ["Aura of Battle"] = 10,
  ["Aura of Command"] = 30,
  ["Aura of Fear"] = 3,
  ["Aural Shock"] = 300,
  ["Awaken Earthen Guardians"] = 5,
  ["Axe Flurry"] = 2,
  ["Axe Toss"] = 3,
  ["Azrethoc's Stomp"] = 5,
  ["Backhand"] = 2,
  ["Balnazzar Transform Stun"] = 5,
  ["Baneful Poison"] = 120,
  ["Banish"] = 30,
  ["Banshee Curse"] = 12,
  ["Banshee Shriek"] = 5,
  ["Barbed Sting"] = 300,
  ["Barrel Explode"] = 3,
  ["Bash"] = 4,
  ["Battle Command"] = 6,
  ["Battle Net"] = 10,
  ["Battle Shout"] = 900,
  ["Battle Standard"] = 3,
  ["Battlegear of Might"] = 6,
  ["Befuddlement"] = 15,
  ["Bellowing Roar"] = 3,
  ["Berserk"] = 30,
  ["Biletoad Infection"] = 180,
  ["Black Arrow"] = 30,
  ["Black March Blessing"] = 6,
  ["Black Rot"] = 1800,
  ["Black Sludge"] = 120,
  ["Blackout"] = 3,
  ["Blast Wave"] = 6,
  ["Blaze"] = 30,
  ["Bleakwood Curse"] = 60,
  ["Blessing of Nordrassil"] = 10,
  ["Blight"] = 60,
  ["Blind"] = 10,
  ["Blink"] = 1,
  ["Blood Howl"] = 15,
  ["Blood Siphon"] = 8,
  ["Bloodfang"] = 6,
  ["Bloodlord's Aura"] = 5,
  ["Bloodlust"] = 15,
  ["Bloodpetal Poison"] = 30,
  ["Boar Charge"] = 1,
  ["Bone Smelt"] = 20,
  ["Bottle of Poison"] = 30,
  ["Boulder"] = 10,
  ["Brain Damage"] = 30,
  ["Brain Hacker"] = 30,
  ["Breath of Sargeras"] = 90,
  ["Brood Affliction: Black"] = 600,
  ["Brood Affliction: Blue"] = 600,
  ["Brood Affliction: Bronze"] = 600,
  ["Brood Affliction: Green"] = 600,
  ["Brood Affliction: Red"] = 600,
  ["Brood Power: Blue"] = 6,
  ["Brood Power: Bronze"] = 5,
  ["Brood Power: Green"] = 6,
  ["Brood Power: Red"] = 5,
  ["Bruising Blow"] = 5,
  ["Burning Adrenaline"] = 20,
  ["Burning Winds"] = 8,
  ["Cadaver Worms"] = 600,
  ["Call of the Grave"] = 60,
  ["Cantation of Manifestation"] = 600,
  ["Capture Felhound Spirit"] = 9,
  ["Capture Infernal Spirit"] = 9,
  ["Capture Spirit"] = 9,
  ["Capture Treant"] = 5,
  ["Cause Insanity"] = 6,
  ["Cauterizing Flames"] = 900,
  ["Chains of Ice"] = 20,
  ["Chains of Kel'Thuzad"] = 20,
  ["Challenging Roar"] = 6,
  ["Challenging Shout"] = 6,
  ["Charge"] = 4,
  ["Charge Stun"] = 1,
  ["Cheap Shot"] = 4,
  ["Chemical Peel"] = 10,
  ["Chill"] = 30,
  ["Chill Nova"] = 10,
  ["Chilled"] = 1.5,
  ["Chilling Breath"] = 12,
  ["Chilling Touch"] = 8,
  ["Chromatic Mutation"] = 300,
  ["Claw Grasp"] = 4,
  ["Clear All Shackels"] = 1,
  ["Cleave Armor"] = 15,
  ["Clenched Pinchers"] = 15,
  ["Cold Eye"] = 15,
  ["Concussion Blow"] = 5,
  ["Concussive Shot"] = 4,
  ["Cone of Cold"] = 8,
  ["Conflagration"] = 10,
  ["Consume"] = 15,
  ["Contagion of Rot"] = 240,
  ["Control Machine"] = 60,
  ["Corrosive Acid"] = 300,
  ["Corrosive Acid Spit"] = 10,
  ["Corrosive Ooze"] = 60,
  ["Corrosive Poison"] = 30,
  ["Corrosive Venom Spit"] = 10,
  ["Corrupted Agility"] = 4,
  ["Corrupted Fear"] = 2,
  ["Corrupted Healing"] = 30,
  ["Corrupted Intellect"] = 4,
  ["Corrupted Stamina"] = 4,
  ["Corrupted Strength"] = 4,
  ["Corrupted Totems"] = 30,
  ["Corruption"] = 18,
  ["Corruption of the Earth"] = 10,
  ["Counterattack"] = 5,
  ["Counterspell"] = 10,
  ["Counterspell - Silenced"] = 4,
  ["Cowering Roar"] = 5,
  ["Cozy Fire"] = 60,
  ["Crash of Waves"] = 10,
  ["Create Heart of Hakkar Explosion"] = 30,
  ["Create Heart of Hakkar Rift"] = 30,
  ["Create Heart of Hakkar Summon Circle"] = 30,
  ["Create Zul's Aura"] = 30,
  ["Creature of Nightmare"] = 30,
  ["Creeper Venom"] = 300,
  ["Creeping Mold"] = 60,
  ["Creeping Plague"] = 20,
  ["Cripple"] = 20,
  ["Crippling Poison"] = 12,
  ["Crowd Pummel"] = 5,
  ["Crusader Strike"] = 30,
  ["Crusader's Hammer"] = 4,
  ["Crush Armor"] = 30,
  ["Crystal Gaze"] = 6,
  ["Crystal Yield"] = 120,
  ["Crystalline Slumber"] = 15,
  ["Curse of Agony"] = 24,
  ["Curse of Blood"] = 600,
  ["Curse of Doom"] = 60,
  ["Curse of Exhaustion"] = 12,
  ["Curse of Hakkar"] = 120,
  ["Curse of Idiocy"] = 120,
  ["Curse of Impotence"] = 120,
  ["Curse of Mending"] = 180,
  ["Curse of Recklessness"] = 120,
  ["Curse of Shadow"] = 300,
  ["Curse of Stalvan"] = 600,
  ["Curse of Thorns"] = 180,
  ["Curse of Thule"] = 240,
  ["Curse of Timmy"] = 60,
  ["Curse of Tongues"] = 30,
  ["Curse of Tuten'kash"] = 900,
  ["Curse of Vengeance"] = 900,
  ["Curse of Weakness"] = 120,
  ["Curse of the Bleakheart"] = 180,
  ["Curse of the Darkmaster"] = 60,
  ["Curse of the Deadwood"] = 120,
  ["Curse of the Dreadmaul"] = 60,
  ["Curse of the Elemental Lord"] = 60,
  ["Curse of the Elements"] = 300,
  ["Curse of the Eye"] = 120,
  ["Curse of the Fallen Magram"] = 900,
  ["Curse of the Firebrand"] = 300,
  ["Curse of the Plague Rat"] = 14,
  ["Curse of the Plaguebringer"] = 10,
  ["Curse of the Shadowhorn"] = 300,
  ["Curse of the Tribes"] = 1800,
  ["Cursed Blade"] = 20,
  ["Cursed Blood"] = 600,
  ["Damage Shield"] = 10,
  ["Dark Energy"] = 300,
  ["Dark Iron Taskmaster Death"] = 6,
  ["Dark Plague"] = 90,
  ["Dark Sludge"] = 300,
  ["Darken Vision"] = 12,
  ["Daunting Growl"] = 30,
  ["Dazed"] = 4,
  ["Deadly Leech Poison"] = 45,
  ["Deadly Poison"] = 12,
  ["Deadly Poison II"] = 12,
  ["Deadly Poison III"] = 12,
  ["Deadly Poison IV"] = 12,
  ["Deadly Poison V"] = 12,
  ["Deadly Toxin"] = 12,
  ["Deadly Toxin II"] = 12,
  ["Deadly Toxin III"] = 12,
  ["Deadly Toxin IV"] = 12,
  ["Deafening Screech"] = 8,
  ["Death Bed"] = 10,
  ["Death Coil"] = 3,
  ["Debilitate"] = 15,
  ["Debilitating Charge"] = 8,
  ["Debilitating Touch"] = 120,
  ["Decayed Agility"] = 300,
  ["Decayed Strength"] = 300,
  ["Decimate"] = 3,
  ["Decrepit Fever"] = 21,
  ["Deep Sleep"] = 10,
  ["Deep Slumber"] = 15,
  ["Deep Wound"] = 12,
  ["Defile"] = 10,
  ["Defiling Aura"] = 5,
  ["Delusions of Jin'do"] = 20,
  ["Demonfork"] = 25,
  ["Demoralize"] = 30,
  ["Demoralizing Roar"] = 30,
  ["Demoralizing Shout"] = 30,
  ["Detect Greater Invisibility"] = 600,
  ["Detect Magic"] = 120,
  ["Detonate Mana"] = 5,
  ["Devilsaur Barb"] = 10,
  ["Devouring Plague"] = 24,
  ["Dire Growl"] = 15,
  ["Dirk's Rememberin' Poison"] = 30,
  ["Disarm"] = 10,
  ["Discombobulate"] = 12,
  ["Disease Buffet"] = 20,
  ["Diseased Shot"] = 300,
  ["Diseased Slime"] = 120,
  ["Diseased Spit"] = 10,
  ["Disjunction"] = 300,
  ["Dismember"] = 10,
  ["Dismounting Shot"] = 2,
  ["Dissolve Armor"] = 20,
  ["Distract Move"] = 7,
  ["Distracting Pain"] = 15,
  ["Distracting Spit"] = 15,
  ["Divine Spirit"] = 1800,
  ["Dominate Mind"] = 10,
  ["Domination"] = 15,
  ["Dominion of Soul"] = 60,
  ["Drain Life"] = 5,
  ["Drain Mana"] = 5,
  ["Drain Soul"] = 15,
  ["Draw Spirit"] = 5,
  ["Draw of Thistlenettle"] = 8,
  ["Dreadful Fright"] = 5,
  ["Dredge Sickness"] = 300,
  ["Drowning Death"] = 300,
  ["Druid's Slumber"] = 15,
  ["Dust Cloud"] = 12,
  ["Eagle Claw"] = 15,
  ["Earth Shock"] = 2,
  ["Earthbind"] = 5,
  ["Earthborer Acid"] = 30,
  ["Earthgrab"] = 4,
  ["Echoing Roar"] = 20,
  ["Ectoplasmic Distiller"] = 3,
  ["Egg Explosion"] = 3,
  ["Electrified Net"] = 10,
  ["Elemental Fire"] = 8,
  ["Elemental Vulnerability"] = 30,
  ["Elixir of the Giants"] = 1200,
  ["Emeriss Aura"] = 10,
  ["Encage"] = 30,
  ["Encasing Webs"] = 6,
  ["Enchanting Lullaby"] = 10,
  ["Encouragement"] = 1800,
  ["Enervate"] = 10,
  ["Enfeeble"] = 120,
  ["Engulfing Flames"] = 6,
  ["Enraging Bite"] = 6,
  ["Enslave"] = 15,
  ["Enslave Demon"] = 300,
  ["Entangle"] = 8,
  ["Entangling Roots"] = 27,
  ["Entrapment"] = 5,
  ["Enveloping Web"] = 8,
  ["Enveloping Webs"] = 8,
  ["Enveloping Winds"] = 10,
  ["Eskhandar's Rake"] = 30,
  ["Essence of the Red"] = 180,
  ["Explode"] = 2.5,
  ["Explode Bug"] = 4,
  ["Explosive Trap Effect"] = 20,
  ["Expose Armor"] = 30,
  ["Expose Weakness"] = 5,
  ["Extract Essence"] = 12,
  ["Eye Peck"] = 12,
  ["Eye of Immol'thar"] = 4,
  ["Faerie Fire"] = 40,
  ["Faerie Fire (Feral)"] = 40,
  ["Fang of the Crystal Spider"] = 10,
  ["Fatal Sting"] = 12,
  ["Fear"] = 20,
  ["Fear (NYI)"] = 15,
  ["Feeblemind"] = 30,
  ["Feeblemind II"] = 30,
  ["Feeblemind III"] = 30,
  ["Fel Stomp"] = 3,
  ["Feral Charge Effect"] = 4,
  ["Festering Bites"] = 1800,
  ["Festering Rash"] = 1800,
  ["Festival Fortune!"] = 1800,
  ["Fevered Fatigue"] = 1800,
  ["Fevered Plague"] = 180,
  ["Fire Festival Fortitude"] = 3600,
  ["Fire Festival Fury"] = 3600,
  ["Fire Protection"] = 3600,
  ["Fire Vulnerability"] = 30,
  ["Fire Weakness"] = 45,
  ["Fireball"] = 8,
  ["Fist of Ragnaros"] = 5,
  ["Five Fat Finger Exploding Heart Technique"] = 30,
  ["Fixate"] = 10,
  ["Flame Buffet"] = 45,
  ["Flame Lash"] = 45,
  ["Flame Shock"] = 12,
  ["Flameshocker's Revenge"] = 2,
  ["Flameshocker's Touch"] = 3,
  ["Flash Freeze"] = 5,
  ["Flesh Rot"] = 10,
  ["Forsaken Skills"] = 300,
  ["Foul Chill"] = 120,
  ["Frailty"] = 60,
  ["Freeze"] = 15,
  ["Freeze III PROC"] = 5,
  ["Freeze Solid"] = 10,
  ["Freezing Claw"] = 5,
  ["Freezing Trap Effect"] = 20,
  ["Frenzied Command"] = 10,
  ["Frenzied Dive"] = 2,
  ["Frightalon"] = 60,
  ["Frightening Shriek"] = 6,
  ["Frost"] = 10,
  ["Frost Aura"] = 5,
  ["Frost Burn"] = 15,
  ["Frost Hold"] = 10,
  ["Frost Nova"] = 8,
  ["Frost Protection "] = 3600,
  ["Frost Shock"] = 8,
  ["Frost Shot"] = 10,
  ["Frost Weakness"] = 45,
  ["Frostbite"] = 5,
  ["Frostbolt"] = 9,
  ["Frostbolt Volley"] = 8,
  ["Frostbrand Attack"] = 8,
  ["Fumble"] = 30,
  ["Fumble II"] = 30,
  ["Fumble III"] = 30,
  ["Fungal Bloom"] = 90,
  ["Garrote"] = 18,
  ["Gehennas' Curse"] = 300,
  ["Geyser"] = 5,
  ["Ghostly Strike"] = 7,
  ["Ghoul Plague"] = 1800,
  ["Ghoul Rot"] = 600,
  ["Gift of Arthas"] = 180,
  ["Gizlock's Dummy Taunt Effect"] = 5,
  ["Glacial Roar"] = 3,
  ["Glimpse of Madness"] = 3,
  ["Gnarlpine Vengeance"] = 6,
  ["Gnomish Death Ray"] = 4,
  ["Gnomish Mind Control Cap"] = 20,
  ["Golemagg's Trust"] = 2,
  ["Gore"] = 15,
  ["Gouge"] = 4,
  ["Grab Weapon"] = 15,
  ["Grasping Vines"] = 10,
  ["Greater Arcane Elixir"] = 1800,
  ["Greater Polymorph"] = 20,
  ["Grip of Command"] = 10,
  ["Ground Smash"] = 3,
  ["Ground Stomp"] = 5,
  ["Ground Tremor"] = 2,
  ["Growl"] = 3,
  ["Gust of Wind"] = 4,
  ["Gutgore Ripper"] = 30,
  ["Hail Storm"] = 3,
  ["Hallow's End Fright"] = 6,
  ["Hammer of Justice"] = 6,
  ["Hamstring"] = 15,
  ["Hand Snap"] = 8,
  ["Hand of Ragnaros"] = 2,
  ["Hand of Thaurissan"] = 5,
  ["Harass"] = 30,
  ["Harsh Winds"] = 1,
  ["Harvest Soul"] = 60,
  ["Hate to Zero"] = 1.7,
  ["Haunting Phantoms"] = 300,
  ["Haunting Spirits"] = 300,
  ["Head Butt"] = 2,
  ["Head Crack"] = 20,
  ["Head Smash"] = 2,
  ["Health II"] = 3600,
  ["Hemorrhage"] = 15,
  ["Hex"] = 10,
  ["Hex of Jammal'an"] = 10,
  ["Hex of Ravenclaw"] = 30,
  ["Hex of Weakness"] = 120,
  ["Hibernate"] = 40,
  ["Highlord's Justice"] = 5,
  ["Hive'Zara Catalyst"] = 30,
  ["Holy Blast"] = 4,
  ["Holy Fire"] = 10,
  ["Holy Protection "] = 3600,
  ["Holy Sunder"] = 60,
  ["Holy Word: Fortitude"] = 1800,
  ["Hooked Net"] = 10,
  ["Howl of Terror"] = 15,
  ["Howling Blade"] = 30,
  ["Howling Rage"] = 300,
  ["Hunter Epic Anti-Cheat DND"] = 60,
  ["Hunter's Mark"] = 120,
  ["Ice Blast"] = 10,
  ["Ice Bolt Prot"] = 5,
  ["Ice Claw"] = 6,
  ["Ice Nova"] = 2,
  ["Ice Tomb"] = 10,
  ["Icebolt"] = 2,
  ["Icicle"] = 10,
  ["Icy Grasp"] = 5,
  ["Ignite"] = 4,
  ["Ignite Flesh"] = 60,
  ["Ignite Mana"] = 300,
  ["Immolate"] = 15,
  ["Immolation Trap Effect"] = 15,
  ["Immunity"] = 1800,
  ["Impact"] = 2,
  ["Impale"] = 9,
  ["Impending Doom"] = 10,
  ["Improved Concussive Shot"] = 3,
  ["Improved Hamstring"] = 5,
  ["Improved Scorpid Sting"] = 20,
  ["Improved Wing Clip"] = 5,
  ["Incapacitating Shout"] = 60,
  ["Incinerate"] = 60,
  ["Incite Flames"] = 60,
  ["Inevitable Doom"] = 10,
  ["Infected Bite"] = 180,
  ["Infected Spine"] = 300,
  ["Infected Wound"] = 300,
  ["Inferno Effect"] = 2,
  ["Inferno Shell"] = 10,
  ["Ink Spray"] = 15,
  ["Insect Swarm"] = 12,
  ["Intellect IX"] = 3600,
  ["Intercept Stun"] = 3,
  ["Interrupt (PT)"] = 30,
  ["Intimidating Growl"] = 5,
  ["Intimidating Roar"] = 8,
  ["Intimidating Shout"] = 8,
  ["Intimidation"] = 3,
  ["Intoxicating Venom"] = 120,
  ["Involuntary Transformation"] = 30,
  ["Irradiated"] = 60,
  ["Itch"] = 8,
  ["Jeff Dummy 1"] = 30,
  ["Jeff Dummy 2"] = 30,
  ["Judge's Gavel"] = 10,
  ["Judgement of Justice"] = 10,
  ["Judgement of Light"] = 10,
  ["Judgement of Wisdom"] = 10,
  ["Judgement of the Crusader"] = 10,
  ["Keg Trap"] = 2,
  ["Kick"] = 5,
  ["Kick - Silenced"] = 2,
  ["Kidney Shot"] = 1,
  ["Knockdown"] = 2,
  ["Knockout"] = 6,
  ["Kodo Stomp"] = 3,
  ["Lacerate"] = 8,
  ["Lacerations"] = 60,
  ["Lag"] = 10,
  ["Larva Goo"] = 6,
  ["Lash"] = 2,
  ["Leech Poison"] = 40,
  ["Lethal Toxin"] = 180,
  ["Life Drain"] = 12,
  ["Lightwell"] = 180,
  ["Living Bomb"] = 8,
  ["Localized Toxin"] = 60,
  ["Locust Swarm"] = 6,
  ["Long Daze"] = 6,
  ["Low Swipe"] = 12,
  ["Lucifron's Curse"] = 300,
  ["Lunaclaw Spirit"] = 120,
  ["Lunar Fortune"] = 1800,
  ["Mace Stun Effect"] = 3,
  ["Magenta Cap Sickness"] = 1200,
  ["Maggot Goo"] = 6,
  ["Maggot Slime"] = 1800,
  ["Magic Reflection"] = 10,
  ["Magma Shackles"] = 15,
  ["Magma Spit"] = 30,
  ["Magma Splash"] = 30,
  ["Malown's Slam"] = 2,
  ["Mana Burn"] = 8,
  ["Mangle"] = 2,
  ["Marduk's Curse"] = 5,
  ["Mark of Arlokk"] = 120,
  ["Mark of Blaumeux"] = 75,
  ["Mark of Detonation"] = 30,
  ["Mark of Flames"] = 120,
  ["Mark of Frost"] = 12,
  ["Mark of Kazzak"] = 60,
  ["Mark of Korth'azz"] = 75,
  ["Mark of Mograine"] = 75,
  ["Mark of Nature"] = 12,
  ["Mark of Zeliek"] = 75,
  ["Mark of the Wild"] = 1800,
  ["Mass Healing"] = 12,
  ["Massive Tremor"] = 2,
  ["Maul"] = 2,
  ["Melt Armor"] = 60,
  ["Melt Ore"] = 20,
  ["Mental Domination"] = 120,
  ["Might of Shahram"] = 5,
  ["Mind Control"] = 60,
  ["Mind Flay"] = 3,
  ["Mind Rot"] = 30,
  ["Mind Shatter"] = 3,
  ["Mind Soothe"] = 15,
  ["Mind Tremor"] = 600,
  ["Mind-numbing Poison"] = 10,
  ["Mind-numbing Poison II"] = 12,
  ["Mind-numbing Poison III"] = 14,
  ["Minor Scorpion Venom Effect"] = 60,
  ["Mirefin Fungus"] = 8,
  ["Miring Mud"] = 5,
  ["Mirkfallon Fungus"] = 2700,
  ["Mobility Malfunction"] = 20,
  ["Mocking Blow"] = 6,
  ["Molten Metal"] = 15,
  ["Moonfire"] = 12,
  ["Mortal Cleave"] = 5,
  ["Mortal Strike"] = 10,
  ["Mortal Wound"] = 15,
  ["Moss Covered Feet"] = 180,
  ["Moss Covered Hands"] = 180,
  ["Muculent Fever"] = 600,
  ["Muscle Tear"] = 5,
  ["Mutate Bug"] = 240,
  ["Mutating Injection"] = 10,
  ["Naralex's Nightmare"] = 15,
  ["Naraxis Web"] = 30,
  ["Nature Protection "] = 3600,
  ["Nature Weakness"] = 45,
  ["Necrotic Poison"] = 30,
  ["Net"] = 10,
  ["Net Guard"] = 20,
  ["Net-o-Matic"] = 10,
  ["Noxious Catalyst"] = 120,
  ["Nullify"] = 8,
  ["Numbing Pain"] = 10,
  ["Oops!"] = 10,
  ["Open Wound Effect"] = 8,
  ["Overseer's Poison"] = 60,
  ["Overwhelming Stench"] = 6,
  ["Pacify"] = 10,
  ["Panic"] = 8,
  ["Paralyze"] = 30,
  ["Paralyzing Poison"] = 8,
  ["Parasite"] = 75,
  ["Parasitic Serpent"] = 10,
  ["Pester Effect"] = 3,
  ["Petrify"] = 8,
  ["Phantom Strike"] = 20,
  ["Pierce Ankle"] = 3,
  ["Pierce Armor"] = 20,
  ["Piercing Howl"] = 6,
  ["Piercing Shadow"] = 1800,
  ["Piercing Shot"] = 15,
  ["Piercing Shriek"] = 6,
  ["Plague"] = 40,
  ["Plague Cloud"] = 240,
  ["Plague Mind"] = 600,
  ["Plague Mist"] = 8,
  ["Planted"] = 3,
  ["Poison"] = 30,
  ["Poison Aura"] = 12,
  ["Poison Bolt"] = 10,
  ["Poison Bolt Volley"] = 10,
  ["Poison Charge"] = 9,
  ["Poison Cloud"] = 45,
  ["Poison Mind"] = 15,
  ["Poison Stinger"] = 10,
  ["Poisoned Harpoon"] = 60,
  ["Poisoned Shot"] = 75,
  ["Poisonous Spit"] = 15,
  ["Poisonous Stab"] = 15,
  ["Polymorph"] = 50,
  ["Polymorph Backfire"] = 8,
  ["Polymorph: Chicken"] = 10,
  ["Polymorph: Cow"] = 50,
  ["Polymorph: Pig"] = 50,
  ["Polymorph: Sheep"] = 10,
  ["Polymorph: Turtle"] = 50,
  ["Polymorphic Ray"] = 4,
  ["Possess"] = 120,
  ["Pounce"] = 2,
  ["Pounce Bleed"] = 18,
  ["Premeditation"] = 10,
  ["Psychic Scream"] = 8,
  ["Pummel"] = 4,
  ["Puncture"] = 10,
  ["Puncture Armor"] = 30,
  ["Purge"] = 2,
  ["Putrid Bile"] = 45,
  ["Putrid Bite"] = 30,
  ["Putrid Breath"] = 30,
  ["Putrid Enzyme"] = 300,
  ["Putrid Stench"] = 10,
  ["Pyroblast"] = 12,
  ["Pyroclasm"] = 3,
  ["Rabid Maw"] = 30,
  ["Rabies"] = 600,
  ["Radiation Poisoning"] = 25,
  ["Rage of Thule"] = 120,
  ["Rake"] = 9,
  ["Rallying Cry of the Dragonslayer"] = 7200,
  ["Rampage"] = 2.5,
  ["Rat Nova"] = 10,
  ["Ravage"] = 2,
  ["Reckless Charge"] = 30,
  ["Reflection Field"] = 5,
  ["Regeneration IV"] = 3600,
  ["Rend"] = 21,
  ["Rend Flesh"] = 12,
  ["Repentance"] = 6,
  ["Repulsive Gaze"] = 8,
  ["Retching Plague"] = 300,
  ["Revenge Stun"] = 3,
  ["Rhahk'Zor Slam"] = 3,
  ["Rift Beacon"] = 60,
  ["Righteous Fire"] = 8,
  ["Rip"] = 12,
  ["Riposte"] = 6,
  ["Riptide"] = 4,
  ["Ritual Candle Aura"] = 6,
  ["Rupture"] = 6,
  ["Sacrifice"] = 8,
  ["Sap"] = 45,
  ["Sap Might"] = 300,
  ["Savage Assault"] = 30,
  ["Savage Assault II"] = 30,
  ["Savage Assault III"] = 30,
  ["Savage Assault IV"] = 30,
  ["Savage Assault V"] = 30,
  ["Savage Pummel"] = 5,
  ["Scald"] = 4,
  ["Scare Beast"] = 20,
  ["Scatter Shot"] = 4,
  ["Scorpid Poison"] = 10,
  ["Scorpid Sting"] = 20,
  ["Screams of the Past"] = 5,
  ["Screech"] = 4,
  ["Searing Blast"] = 30,
  ["Searing Flames"] = 9,
  ["Seduction"] = 15,
  ["Seeping Willow"] = 30,
  ["Serious Wound"] = 10,
  ["Serpent Sting"] = 15,
  ["Serrated Bite"] = 30,
  ["Shackle Undead"] = 50,
  ["Shadow Bolt"] = 6,
  ["Shadow Command"] = 15,
  ["Shadow Flame"] = 10,
  ["Shadow Mark"] = 15,
  ["Shadow Protection "] = 3600,
  ["Shadow Vulnerability"] = 15,
  ["Shadow Weakness"] = 45,
  ["Shadow Word: Pain"] = 18,
  ["Shadow of Ebonroc"] = 8,
  ["Shadowburn"] = 5,
  ["Shadowstalker Slash"] = 5,
  ["Shadowstalker Stab"] = 5,
  ["Shared Bonds"] = 4,
  ["Shazzrah's Curse"] = 300,
  ["Shield Bash"] = 6,
  ["Shield Bash - Silenced"] = 3,
  ["Shield Slam"] = 2,
  ["Shockwave"] = 2,
  ["Shred"] = 12,
  ["Shrink"] = 120,
  ["Shrink Ray"] = 20,
  ["Silence"] = 5,
  ["Silithid Pox"] = 1800,
  ["Siphon Blessing"] = 30,
  ["Siphon Health"] = 15,
  ["Siphon Life"] = 30,
  ["Skull Crack"] = 2,
  ["Skullforge Brand"] = 30,
  ["Slam"] = 2,
  ["Slavedriver's Cane"] = 30,
  ["Sleep"] = 30,
  ["Sleepwalk"] = 10,
  ["Slice and Dice"] = 6,
  ["Slime Bolt"] = 6,
  ["Slime Burst"] = 5,
  ["Slime Dysentery"] = 1800,
  ["Slime Stream"] = 3,
  ["Sling Dirt"] = 10,
  ["Sling Mud"] = 15,
  ["Sloth Effect"] = 3,
  ["Slow"] = 15,
  ["Slow Poison"] = 30,
  ["Slow Poison II"] = 30,
  ["Slowing Ooze"] = 10,
  ["Slowing Poison"] = 25,
  ["Sludge"] = 3,
  ["Sludge Toxin"] = 45,
  ["Smite Demon"] = 5,
  ["Smite Slam"] = 3,
  ["Smite Stomp"] = 10,
  ["Smoke Bomb"] = 4,
  ["Smoke Cloud"] = 3,
  ["Smother"] = 6,
  ["Snap Kick"] = 2,
  ["Sol L"] = 5,
  ["Sonic Burst"] = 10,
  ["Soot Covering"] = 10,
  ["Soothe Animal"] = 15,
  ["Soul Breaker"] = 30,
  ["Soul Burn"] = 16,
  ["Soul Corruption"] = 15,
  ["Soul Drain"] = 10,
  ["Soul Revival"] = 1800,
  ["Soul Siphon"] = 10,
  ["Soul Tap"] = 12,
  ["Spell Lock"] = 8,
  ["Spell Vulnerability"] = 5,
  ["Spider Poison"] = 30,
  ["Spider Web"] = 1,
  ["Spider's Kiss"] = 10,
  ["Spirit Decay"] = 1200,
  ["Spirit of Zandalar"] = 7200,
  ["Spitelash"] = 20,
  ["Starfire Stun"] = 3,
  ["Starshards"] = 6,
  ["Stasis Effect"] = 15,
  ["Stasis Test"] = 5,
  ["Static Conduit"] = 15,
  ["Steam Jet"] = 10,
  ["Sticky Tar"] = 4,
  ["Stink Trap"] = 120,
  ["Stomp"] = 10,
  ["Storm Bolt"] = 8,
  ["Stormbolt"] = 5,
  ["Stormstrike"] = 12,
  ["Strong Cleave"] = 10,
  ["Stun"] = 2,
  ["Stunning Blast"] = 5,
  ["Stunning Blow"] = 8,
  ["Stunning Strike"] = 4,
  ["Stygian Grasp"] = 5,
  ["Submersion"] = 60,
  ["Sul'thraze"] = 15,
  ["Summon Darrowshire Spirit"] = 60,
  ["Summon Finkle Generator"] = 5,
  ["Summon Freed Soul"] = 60,
  ["Summon Healed Celebrian Vine"] = 604800,
  ["Summon Isalien DND"] = 600,
  ["Summon Jarien and Sothos DND"] = 600,
  ["Summon Knight"] = 180,
  ["Summon Kormok DND"] = 600,
  ["Summon Lord Valthalak DND"] = 600,
  ["Summon Marduk the Black"] = 300,
  ["Summon Mor Grayhoof DND"] = 600,
  ["Summon Mounted Knight"] = 120,
  ["Summon Screecher Spirit"] = 120,
  ["Summon Thelrin DND"] = 600,
  ["Summon Trainee"] = 230,
  ["Summon Various DND"] = 600,
  ["Sunder Armor"] = 30,
  ["Sundering Cleave"] = 30,
  ["Super Shrink Ray"] = 20,
  ["Surprise Attack"] = 2.5,
  ["Survival Instinct"] = 2,
  ["TWEEP"] = 11,
  ["Taelan's Suffering Effect"] = 2,
  ["Tail Lash"] = 2,
  ["Tainted Blood Effect"] = 10,
  ["Tainted Mind"] = 600,
  ["Tame Adult Plainstrider"] = 900,
  ["Tame Armored Scorpid"] = 900,
  ["Tame Beast"] = 20,
  ["Tame Dire Mottled Boar"] = 900,
  ["Tame Ice Claw Bear"] = 20,
  ["Tame Large Crag Boar"] = 20,
  ["Tame Nightsaber Stalker"] = 900,
  ["Tame Prairie Stalker"] = 900,
  ["Tame Snow Leopard"] = 900,
  ["Tame Strigid Screecher"] = 900,
  ["Tame Surf Crawler"] = 900,
  ["Tame Swoop"] = 900,
  ["Tame Webwood Lurker"] = 900,
  ["Target Dummy Spawn Effect"] = 5,
  ["Taunt"] = 3,
  ["Tendon Rip"] = 8,
  ["Tendon Slice"] = 8,
  ["Tendrils of Air"] = 2,
  ["Terrify"] = 4,
  ["Terrifying Howl"] = 3,
  ["Terrifying Roar"] = 5,
  ["Terrifying Screech"] = 4,
  ["Test Curse of Agony"] = 24,
  ["Test Rip"] = 12,
  ["Test Strike W35"] = 10,
  ["Test Strike W50"] = 10,
  ["Tetanus"] = 1200,
  ["Thorn Volley"] = 2,
  ["Thorns"] = 600,
  ["Threatening Gaze"] = 6,
  ["Threatening Growl"] = 30,
  ["Throw Axe"] = 2,
  ["Thunder Clap"] = 30,
  ["Thunderclap"] = 10,
  ["Thundercrack"] = 2.5,
  ["Thunderfury"] = 12,
  ["Thundershock"] = 5,
  ["Tidal Charm"] = 3,
  ["Tight Pinch"] = 5,
  ["Time Lapse"] = 8,
  ["Torch Burst"] = 30,
  ["Torch Toss"] = 30,
  ["Tornado"] = 4,
  ["Touch of Ravenclaw"] = 5,
  ["Touch of Weakness"] = 120,
  ["Toxic Contagion"] = 60,
  ["Toxic Saliva"] = 120,
  ["Toxic Volley"] = 15,
  ["Tranquilizing Poison"] = 8,
  ["Trap"] = 10,
  ["Trelane's Freezing Touch"] = 12,
  ["Trip"] = 3,
  ["True Fulfillment"] = 20,
  ["Tunneler Acid"] = 30,
  ["Turn Undead"] = 20,
  ["Twisted Reflection"] = 45,
  ["Unbalancing Strike"] = 6,
  ["Unholy Curse"] = 12,
  ["Vampiric Embrace"] = 60,
  ["Vanish"] = 20,
  ["Veil of Darkness"] = 7,
  ["Veil of Shadow"] = 15,
  ["Vekniss Catalyst"] = 30,
  ["Vengeance"] = 600,
  ["Venom Spit"] = 10,
  ["Venom Sting"] = 45,
  ["Venomhide Poison"] = 30,
  ["Vicious Rend"] = 15,
  ["Vindication"] = 10,
  ["Viper Sting"] = 8,
  ["Virulent Poison"] = 30,
  ["Vital Wound"] = 8,
  ["Void Bolt"] = 10,
  ["Volatile Infection"] = 120,
  ["Voodoo Hex"] = 120,
  ["Vulnerable"] = 3,
  ["Wail of Nightlash"] = 15,
  ["Wail of the Banshee"] = 12,
  ["Wailing Dead"] = 6,
  ["Wandering Plague"] = 300,
  ["War Stomp"] = 2,
  ["Warchief's Blessing"] = 3600,
  ["Ward of Laze effect"] = 3,
  ["Warlock Terror"] = 2,
  ["Water Breathing"] = 600,
  ["Wavering Will"] = 60,
  ["Weak Poison"] = 12,
  ["Weakening Disease"] = 30,
  ["Web"] = 8,
  ["Web Explosion"] = 10,
  ["Web II"] = 10,
  ["Web III"] = 12,
  ["Web Spin"] = 7,
  ["Web Spray"] = 10,
  ["Whipweed Entangle"] = 18,
  ["Whipweed Roots"] = 15,
  ["Whirling Trip"] = 2,
  ["Whirlwind"] = 2,
  ["Whisperings of C'Thun"] = 20,
  ["Widow Bite"] = 4,
  ["Widow's Embrace"] = 30,
  ["Wild Magic"] = 30,
  ["Wild Polymorph"] = 20,
  ["Will of Hakkar"] = 20,
  ["Windreaper"] = 20,
  ["Windsor Dismisses Horse DND"] = 55,
  ["Wing Clip"] = 10,
  ["Wings of Despair"] = 6,
  ["Winter's Chill"] = 15,
  ["Wither"] = 21,
  ["Wither Strike"] = 8,
  ["Wither Touch"] = 120,
  ["Withered Touch"] = 180,
  ["Withering Heat"] = 900,
  ["Withering Poison"] = 180,
  ["Wound"] = 25,
  ["Wound Poison"] = 15,
  ["Wracking Pains"] = 180,
  ["Wrath of the Plaguebringer"] = 10,
  ["Wyvern Sting"] = 12,
  ["[PH] Crystal Corpse Timer"] = 7200,
  ["scaler test"] = 10,
}

-- ---------------------------------------------------------------------------
-- Player-dependent adjustments
--
-- A few durations are not a property of the spell alone. pfUI applies these
-- from libdebuff:GetDuration; they are ported with one addition -- each is
-- gated on the player's class. pfUI reads the talent position blind, and two
-- of these positions collide across classes (warrior 2/1 Booming Voice and
-- rogue 2/1 Improved Gouge), so an ungated read gives a rogue watching a
-- warrior mob's Demoralizing Shout the wrong number.
--
-- The gate is a narrowing, not a fix: the talent bonus only applies when the
-- player cast the aura, and no caster is recoverable for a target aura on this
-- client (auras.no_native_debuff_expiry_time). A warrior watching another
-- warrior's Demoralizing Shout still gets their own Booming Voice rank applied
-- to it. That is the same limit pfUI carries.
-- ---------------------------------------------------------------------------
local function Call(name, a, b)
  local fn = U.G(name)
  if type(fn) ~= "function" then return nil end
  local ok, v1, v2, v3, v4, v5 = pcall(fn, a, b)
  if not ok then return nil end
  return v1, v2, v3, v4, v5
end

local function PlayerClass()
  local _, class = Call("UnitClass", "player")
  return type(class) == "string" and class or nil
end

local function ComboPoints()
  return tonumber(Call("GetComboPoints")) or 0
end

-- GetTalentInfo's fifth return is the number of points spent.
local function TalentRank(tab, index)
  local _, _, _, _, count = Call("GetTalentInfo", tab, index)
  return tonumber(count) or 0
end

local function Adjust(name, duration)
  local class = PlayerClass()

  if name == "Rupture" and class == "ROGUE" then
    return duration + ComboPoints() * 2
  elseif name == "Kidney Shot" and class == "ROGUE" then
    return duration + ComboPoints()
  elseif name == "Gouge" and class == "ROGUE" then
    return duration + TalentRank(2, 1) * 0.5
  elseif name == "Demoralizing Shout" and class == "WARRIOR" then
    -- Booming Voice: +10% of the base per point.
    return duration + duration / 100 * (TalentRank(2, 1) * 10)
  elseif name == "Shadow Word: Pain" and class == "PRIEST" then
    return duration + TalentRank(3, 4) * 3
  elseif name == "Frostbolt" and class == "MAGE" then
    -- Permafrost: +1s per point.
    return duration + TalentRank(3, 7)
  end

  return duration
end

-- Seconds this aura should run for, or nil when the table has no entry --
-- which is the signal modules/auras.lua uses to draw no timer at all rather
-- than to invent one.
function U.AuraDuration(name)
  if type(name) ~= "string" or name == "" then return nil end

  local base = DURATION[name]
  if not base or base <= 0 then return nil end

  local adjusted = Adjust(name, base)
  if type(adjusted) ~= "number" or adjusted <= 0 then return base end
  return adjusted
end

-- How much the table actually covers, reported through U.AuraStats so
-- "/uui perf" can answer "why does this aura have no timer" with a number.
-- Counted once at load rather than per read: the walk is 900-odd keys and the
-- answer never changes.
local count = 0
local _
for _ in pairs(DURATION) do count = count + 1 end

function U.AuraDurationCount()
  return count
end
